### PR TITLE
use golang_1.6.2

### PR DESCRIPTION
**Pull request by jianqiu**
Removed golang_1.5.3,  begin to use golang_1.6.2

### CODE REVIEW

**Comment by maximilien** [comment]
@jianqiu has this passed CI? Confirm and I will merge.

**Comment by jianqiu** [comment]
@maximilien , CI had already passed. Thanks!

**Comment by jianqiu** [comment]
@maximilien  Could you please review it? It is ready to be merged. Thanks!

**Comment by maximilien** [comment]
Cool, thank you @jianqiu. Merging, cheers 👍

**Pull request merged**
