### PR TITLE
fix some issue

### PR DESCRIPTION
**Pull request by ghost**
Dear, 
When use bosh-init with softlayer eCPI , need to add the following SL  spec properties .

Thanks!

### CODE REVIEW

**Comment by cppforlife** [comment]
Please include description for each required value.

Also remove extra blank lines.

**Comment by maximilien** [comment]
@wen-quan, please address @cppforlife comments.

Thanks.

**Comment by ghost** [comment]
@maximilien @cppforlife 
Done with your requirements. Thanks!

**Comment by maximilien** [comment]
Thanks @wen-quan. Cheers :beers:

**Pull request merged**
